import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { connect } from "react-redux";
import { addAction } from '../store/action'

function Home(props) {
  console.log("props: ", props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>
      This is a pre-rendered page. The current number in state is: {props.number}
      </h1>

      <button onClick={() => props.add()}>
        Click here to increment your number.
      </button>

      <br/>
      <Link href={"/add"} >
        Go to add page
      </Link>
      <br/>
      <Link href={"/sub"} >
        Go to sub page
      </Link>
    </div>
  )
}

const mapStateToProps = (state) => {

    return {
        number: state.rootReducer.number,
    }
}

const mapDispatchToProps = (dispatch) => {
    return {
      add: () => dispatch(addAction())
    };
};

export default connect(mapStateToProps,mapDispatchToProps)(Home);