import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { wrapper } from "../store/store";
import { connect } from "react-redux";
import { subAction } from '../store/action'

function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>
          This Page is Server Side Rendered. The number should go down when you navigate to this page. The dispatch happens on the server side. The current number in state is: {props.number}
      </h1>


      <button onClick={() => props.sub()}>
        Click here to decrement your number
      </button>

      <br/>
      <Link href={"/add"} >
        Go to add page
      </Link>

      <br/>

      <Link href={"/sub"} >
        Go to sub page
      </Link>
    </div>
  )
}


const mapStateToProps = (state) => {

  return {
    number: state.rootReducer.number,
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    sub: () => dispatch(subAction())
  };
};

export default connect(mapStateToProps,mapDispatchToProps)(Home);

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  store.dispatch(subAction());
});
